spring.application.name=list-set-difference

server.port=8082
server.servlet.context-path=/list-set-difference

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


